version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: rabbit_user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "0.0.0.0:5672:5672" # RabbitMQ server
      - "15672:15672" # Management interface